import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: "Overview",
    trainingVideos: "Training Modules",
    documentSearch: "Knowledge Base",
    imageLibrary: "Asset Library",
    faqs: "Support & FAQs",
    settings: "Preferences",
    newChat: "New Inquiry",
    online: "Online",
    searchPlaceholder: "Search internal resources...",
    askPrompt: "Ask questions, search internal knowledge, and generate responses.",
    tipEnter: "Tip: Press Enter to send.",
    totalImages: "Total Images",
    filteredImages: "Filtered",
    imageSearchPlaceholder: "Search by product name or filename (e.g. 'plier', 'disc')...",
    copyName: "Copy Product Name",
    copyFilename: "Copy Filename",
    downloadImage: "Download Image",
    lockedPortal: "Secure Video Portal",
    lockedSub: "Enter your company email and security code to access Selecta's proprietary training videos.",
    emailLabel: "Company Email",
    passLabel: "Security Password",
    accessBtn: "Access Training Portal",
    confidentialAlertTitle: "⚠️ Proprietary Company Asset",
    confidentialAlertDesc: "These training videos contain internal logistics, safety techniques, and proprietary methodologies of Selecta Marketing (Pvt) Ltd. Sharing, recorded copying, or distribution is strictly prohibited.",
    videoStreamTitle: "Company Training Videos",
    videoStreamSub: "Access step-by-step video logs on hardware tool handling, adjustments, and safety procedures.",
    logout: "Lock Portal",
    noVidSelectedTitle: "No Video Selected",
    noVidSelectedSub: "Choose a training course from the left menu to start the secure streaming player.",
    confidentialOverlay: "SELECTA INTERNAL PROPERTY - DO NOT LEAK",
    faqTitle: "FAQs & Tools Catalog",
    faqSub: "Quick answers and a searchable list of Selecta hardware tools (codes + item names).",
    docTitle: "Knowledge Base & Document Search",
    docSub: "Search internal guides, product operating manuals, and standard safety documentation.",
    quickView: "Quick View",
    clearFilters: "Clear Filters",
    statsHeader: "Browse, search, and preview high-resolution product photos from the database.",
    filenameLabel: "Filename",
    pathLabel: "Asset Relative Path",
    totalProgress: "Total Progress",
    passedStatus: "Passed",
    reviewBtn: "Review",
    startBtn: "Start",
    durationLabel: "duration",
    completedBadge: "Module Completed!",
    finalQuizTitle: "Final Module Quiz",
    knowledgeAssess: "Knowledge Assessment",
    quizSub: "Score at least 70% to pass and complete the course.",
    submitAnswers: "Submit Answers",
    backDashboard: "Back to Dashboard",
    congratsTitle: "Congratulations! You Passed",
    failedTitle: "Oops! You Didn't Pass",
    scoreSummary: "You scored {score} out of {total} correct answers ({percentage}%).",
    tryAgain: "Try Quiz Again",
    nextSlide: "Next Slide",
    takeQuiz: "Take Quiz",
    previousBtn: "Previous",
    exitCourse: "Exit Course",
    demoCreds: "Demo Credentials",
    streamSecurity: "Stream Security: HTTPS Encrypted",
    assetIdLabel: "Asset ID",
    videoPlayingLabel: "SECURE BROADCAST",
    videoPausedLabel: "PAUSED",
    allCategoryTab: "All",
    searchPlaceholderDoc: "Search documents content...",
    docSectionSummary: "Summary",
    noDocSelectedTitle: "No Document Selected",
    noDocSelectedSub: "Select a document from the left list to read its contents.",
    askAiBtn: "Ask Selecta AI",
    contactHeading: "SELECTA MARKETING (PVT) LTD",
    contactSub: "No 19, Anagarika Dharmapala Mawatha, Galle",
    contactPhone: "Phone: 0773246100 / 0912238380",
    contactEmail: "Email: selectamarketing.pvt.ltd@gmail.com",
    faqSearchPlaceholder: "Search (e.g., '2502', 'plier', 'tape')",
    faqTableCode: "Code",
    faqTableName: "Item Name",
    faqTableCategory: "Category",
    faqNoItems: "No items found.",
    faqFooterNote: "You can extend this page with prices later (if you provide price columns).",
    settingsTitle: "Settings",
    settingsSub: "Manage your profile, assistant behavior, notifications, and privacy.",
    settingsReset: "Reset",
    settingsSave: "Save Changes",
    profileTitle: "Profile",
    profileSub: "Basic information used in the application.",
    fullNameLabel: "Full name",
    emailFieldLabel: "Email",
    roleLabel: "Role",
    assistantTitle: "Assistant",
    assistantSub: "Control how Selecta AI responds and behaves.",
    responseToneLabel: "Response tone",
    toggleSources: "Include sources (when available)",
    toggleSourcesSub: "Show references/links when the assistant uses documents.",
    toggleScroll: "Auto-scroll chat",
    toggleScrollSub: "Automatically scroll to the newest message.",
    notifTitle: "Notifications",
    notifSub: "Choose how you want to be notified.",
    toggleEmailAlerts: "Email alerts",
    toggleEmailAlertsSub: "Receive updates to your email.",
    toggleDesktopAlerts: "Desktop alerts",
    toggleDesktopAlertsSub: "Show notifications in your browser (requires permission).",
    privacyTitle: "Privacy",
    privacySub: "Control what is saved on this device.",
    toggleSaveHistory: "Save chat history on this device",
    toggleSaveHistorySub: "Stores chat messages in memory only for now. (You can add database later.)",
    localStorageNote: "Note: This demo stores settings in localStorage. If you add a backend later, we can save these settings per user account.",
    appearanceTitle: "Appearance",
    appearanceSub: "UI preferences.",
    toggleCompact: "Compact mode",
    toggleCompactSub: "Reduce spacing for dense screens.",
    sessionUnlocked: "Session Unlocked"
  },
  si: {
    dashboard: "පාලක පුවරුව",
    trainingVideos: "පුහුණු වීඩියෝ",
    documentSearch: "ලේඛන සෙවීම",
    imageLibrary: "ඡායාරූප එකතුව",
    faqs: "නිතර අසන ප්‍රශ්න",
    settings: "සැකසුම්",
    newChat: "නව සංවාදයක්",
    online: "සක්‍රීයයි",
    searchPlaceholder: "අභ්‍යන්තර සම්පත් සොයන්න...",
    askPrompt: "ප්‍රශ්න අසන්න, අභ්‍යන්තර දැනුම සොයන්න, සහ පිළිතුරු ලබා ගන්න.",
    tipEnter: "ඉඟිය: යැවීමට Enter ඔබන්න.",
    totalImages: "මුළු ඡායාරූප",
    filteredImages: "පෙරූ ප්‍රමාණය",
    imageSearchPlaceholder: "නිෂ්පාදන නම හෝ ගොනු නාමයෙන් සොයන්න (උදා: 'plier', 'disc')...",
    copyName: "නිෂ්පාදන නම පිටපත් කරන්න",
    copyFilename: "ගොනු නම පිටපත් කරන්න",
    downloadImage: "ඡායාරූපය බාගත කරන්න",
    lockedPortal: "ආරක්ෂිත වීඩියෝ ද්වාරය",
    lockedSub: "සෙලෙක්ටා හි හිමිකාර පුහුණු වීඩියෝ නැරඹීමට ඔබේ සමාගමේ විද්‍යුත් තැපෑල සහ මුරපදය ඇතුළත් කරන්න.",
    emailLabel: "සමාගමේ විද්‍යුත් තැපෑල",
    passLabel: "ආරක්ෂක මුරපදය",
    accessBtn: "පුහුණු ද්වාරයට පිවිසෙන්න",
    confidentialAlertTitle: "⚠️ හිමිකාර ආයතනික දේපලකි",
    confidentialAlertDesc: "මෙම පුහුණු වීඩියෝවල සෙලෙක්ටා මාර්කටින් ආයතනයේ අභ්‍යන්තර මෙහෙයුම්, ආරක්ෂක ශිල්පීය ක්‍රම සහ රහස්‍ය ක්‍රමවේද අඩංගු වේ. බෙදා හැරීම හෝ පටිගත කර පිටපත් කිරීම සපුරා තහනම් වේ.",
    videoStreamTitle: "ආයතනික පුහුණු වීඩියෝ",
    videoStreamSub: "මෙවලම් හැසිරවීම, ගැලපීම් සහ ආරක්ෂක පියවර පිළිබඳ වීඩියෝ මෙහි ඇත.",
    logout: "ද්වාරය වසන්න",
    noVidSelectedTitle: "කිසිදු වීඩියෝවක් තෝරා නැත",
    noVidSelectedSub: "ආරම්භ කිරීමට වම්පස මෙනුවෙන් වීඩියෝවක් තෝරන්න.",
    confidentialOverlay: "සෙලෙක්ටා අභ්‍යන්තර දේපලකි - කාන්දු නොකරන්න",
    faqTitle: "නිතර අසන ප්‍රශ්න සහ මෙවලම් නාමාවලිය",
    faqSub: "සෙලෙක්ටා මෙවලම්වල කේත සහ විස්තර මෙහි සොයන්න.",
    docTitle: "දැනුම් පදනම සහ ලේඛන සෙවීම",
    docSub: "අභ්‍යන්තර මෙහෙයුම් අත්පොත් සහ ආරක්ෂක මාර්ගෝපදේශ සොයන්න.",
    quickView: "නරඹන්න",
    clearFilters: "පෙරහන් ඉවත් කරන්න",
    statsHeader: "දත්ත ගබඩාවේ ඇති සියලුම නිෂ්පාදන ඡායාරූප මෙහි ගවේෂණය කර සොයන්න.",
    filenameLabel: "ගොනු නාමය",
    pathLabel: "ගොනු පිහිටීම (Path)",
    totalProgress: "මුළු ප්‍රගතිය",
    passedStatus: "සමත්",
    reviewBtn: "සමාලෝචනය",
    startBtn: "ආරම්භ කරන්න",
    durationLabel: "කාලය",
    completedBadge: "මොඩියුලය සම්පූර්ණයි!",
    finalQuizTitle: "අවසාන ප්‍රශ්නාවලිය",
    knowledgeAssess: "දැනුම ඇගයීම",
    quizSub: "සමත් වීමට අවම වශයෙන් 70% ක් ලබා ගන්න.",
    submitAnswers: "පිළිතුරු ඉදිරිපත් කරන්න",
    backDashboard: "පාලක පුවරුවට",
    congratsTitle: "සුභ පැතුම්! ඔබ සමත්",
    failedTitle: "කණගාටුයි! ඔබ සමත් නැත",
    scoreSummary: "ඔබ නිවැරදි පිළිතුරු {score} න් {total} ක් ලබා ගත්තා ({percentage}%).",
    tryAgain: "නැවත උත්සාහ කරන්න",
    nextSlide: "මීළඟ පිටුව",
    takeQuiz: "ප්‍රශ්නාවලිය",
    previousBtn: "පෙර පිටුව",
    exitCourse: "පිටවීම",
    demoCreds: "නිරූපණ ගිණුම්",
    streamSecurity: "ආරක්ෂාව: HTTPS සංකේතනය කර ඇත",
    assetIdLabel: "අයිතම කේතය (Asset ID)",
    videoPlayingLabel: "ආරක්ෂිත විකාශනය",
    videoPausedLabel: "නවතලා ඇත",
    allCategoryTab: "සියල්ල",
    searchPlaceholderDoc: "ලේඛන අන්තර්ගතයන් සොයන්න...",
    docSectionSummary: "සාරාංශය",
    noDocSelectedTitle: "කිසිදු ලේඛනයක් තෝරා නැත",
    noDocSelectedSub: "අන්තර්ගතය කියවීම සඳහා වම්පස ලැයිස්තුවෙන් ලේඛනයක් තෝරන්න.",
    askAiBtn: "සෙලෙක්ටා AI වෙතින් අසන්න",
    contactHeading: "සෙලෙක්ටා මාර්කටින් (පුද්) සමාගම",
    contactSub: "නො. 19, අනගාරික ධර්මපාල මාවත, ගාල්ල",
    contactPhone: "දුරකථන: 0773246100 / 0912238380",
    contactEmail: "විද්‍යුත් තැපෑල: selectamarketing.pvt.ltd@gmail.com",
    faqSearchPlaceholder: "සොයන්න (උදා: '2502', 'ප්ලයර්', 'ටේප්')",
    faqTableCode: "කේතය",
    faqTableName: "භාණ්ඩයේ නම",
    faqTableCategory: "වර්ගය",
    faqNoItems: "කිසිවක් හමු නොවීය.",
    faqFooterNote: "ඔබට පසුව මිල ගණන් මෙම සටහනට ඇතුළත් කළ හැකිය.",
    settingsTitle: "සැකසුම්",
    settingsSub: "ඔබේ පැතිකඩ, සහකාර හැසිරීම, දැනුම්දීම් සහ රහස්‍යතාව කළමනාකරණය කරන්න.",
    settingsReset: "නැවත සකසන්න",
    settingsSave: "සැකසුම් සුරකින්න",
    profileTitle: "පැතිකඩ",
    profileSub: "යෙදුමේ භාවිත වන මූලික තොරතුරු.",
    fullNameLabel: "සම්පූර්ණ නම",
    emailFieldLabel: "විද්‍යුත් තැපෑල",
    roleLabel: "තනතුර",
    assistantTitle: "සහකාර AI",
    assistantSub: "සෙලෙක්ටා AI සහකාරගේ හැසිරීම් පාලනය කරන්න.",
    responseToneLabel: "පිළිතුරු විලාසය",
    toggleSources: "මූලාශ්‍ර ඇතුළත් කරන්න (ඇත්නම් පමණක්)",
    toggleSourcesSub: "සහකාර ලේඛන භාවිත කරන විට ඒවායේ සබැඳි පෙන්වන්න.",
    toggleScroll: "ස්වයංක්‍රීයව පහළට යන්න",
    toggleScrollSub: "නව පණිවිඩ ලැබෙන විට ස්වයංක්‍රීයව පහළට යන්න.",
    notifTitle: "දැනුම්දීම්",
    notifSub: "ඔබට දැනුම්දීම් ලැබිය යුතු ආකාරය තෝරන්න.",
    toggleEmailAlerts: "ඊමේල් දැනුම්දීම්",
    toggleEmailAlertsSub: "ඔබේ ඊමේල් ලිපිනයට යාවත්කාලීන කිරීම් ලබා ගන්න.",
    toggleDesktopAlerts: "ඩෙස්ක්ටොප් දැනුම්දීම්",
    toggleDesktopAlertsSub: "බ්‍රවුසරයේ දැනුම්දීම් පෙන්වන්න (අවසර අවශ්‍ය වේ).",
    privacyTitle: "රහස්‍යතාව",
    privacySub: "මෙම උපාංගයේ සුරකින දෑ පාලනය කරන්න.",
    toggleSaveHistory: "සංවාද ඉතිහාසය මෙම උපාංගයේ සුරකින්න",
    toggleSaveHistorySub: "සංවාද මතකයේ පමණක් තාවකාලිකව සුරකියි (පසුව දත්ත සමුදායක් එක් කළ හැක).",
    localStorageNote: "සටහන: මෙම සැකසුම් localStorage හි සුරැකේ. පසුව backend එකක් එක් කළ විට පරිශීලක ගිණුමට අනුව සුරැකිය හැක.",
    appearanceTitle: "පෙනුම",
    appearanceSub: "පෙනුම පිළිබඳ සැකසුම්.",
    toggleCompact: "සංයුක්ත ප්‍රකාරය (Compact mode)",
    toggleCompactSub: "කුඩා තිර සඳහා ඉඩ ඉතිරි කරන්න.",
    sessionUnlocked: "සැසිය විවෘතයි"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("selecta_lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("selecta_lang", lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
